In [72]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import warnings
import io

In [73]:
data = """รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-23
64002,สมหญิง,21.0,หญิง,วิทย์,3.45,165.0,58.0,20.0,2024-02-05
64003,,,Male,Science,3.67,175.0,,25.0,2024-01-13
64004,สมศักดิ์,22.0,ช,คณะวิทยาศาสตร์,-1.0,168.0,70.0,10.0,2023-12-30
64005,สมใจ,19.0,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-27
64006,กานต์,150.0,ชาย,Engineering,3.12,172.0,75.0,12.0,2023-12-23
64007,กิตติ,21.0,หญิง,วิศวกรรม,4.5,158.0,48.0,35.0,2024-01-05
64008,จิรา,20.0,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-01-23
64009,ชนาธิป,23.0,M,Arts,3.34,163.0,55.0,22.0,2024-02-11
64010,ดารา,21.0,หญิง,ศิลป์,3.56,167.0,60.0,28.0,2024-01-03
64011,ธีระ,,,,3.78,,68.0,,2024-01-07
64012,นภา,22.0,ชาย,วิทย์,,171.0,,16.0,2023-12-26
64013,บุญมี,20.0,หญิง,วิศวฯ,3.23,169.0,72.0,24.0,2023-12-26
64014,ปรีชา,21.0,ชาย,Liberal Arts,3.45,164.0,54.0,19.0,2024-01-08
64015,พิมพ์,22.0,Female,Sci,3.67,162.0,56.0,26.0,2024-02-06
64016,ภูมิ,19.0,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-20
64017,มานี,20.0,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-24
64018,ยุพา,21.0,หญิง,,3.23,161.0,50.0,27.0,2024-01-08
64019,รัตนา,,ชาย,ศิลปศาสตร์,,174.0,76.0,,2023-12-18
64020,ลัดดา,22.0,,Science,3.45,168.0,64.0,23.0,2024-01-06"""

In [74]:
data_io = io.StringIO(data)
df = pd.read_csv(data_io)

In [75]:
print(df.head)

<bound method NDFrame.head of     รหัสนักศึกษา      ชื่อ   อายุ     เพศ             คณะ   GPA  ส่วนสูง_cm  \
0          64001     สมชาย   20.0     ชาย     วิทยาศาสตร์  3.21       170.0
1          64002    สมหญิง   21.0    หญิง           วิทย์  3.45       165.0
2          64003       NaN    NaN    Male         Science  3.67       175.0
3          64004  สมศักดิ์   22.0       ช  คณะวิทยาศาสตร์ -1.00       168.0
4          64005      สมใจ   19.0       ญ           วิศวะ  3.89       160.0
5          64006     กานต์  150.0     ชาย     Engineering  3.12       172.0
6          64007     กิตติ   21.0    หญิง        วิศวกรรม  4.50       158.0
7          64008      จิรา   20.0       F      ศิลปศาสตร์  2.98       180.0
8          64009    ชนาธิป   23.0       M            Arts  3.34       163.0
9          64010      ดารา   21.0    หญิง           ศิลป์  3.56       167.0
10         64011      ธีระ    NaN     NaN             NaN  3.78         NaN
11         64012       นภา   22.0     ชาย           วิทย์   NaN       171.0
12         64013     บุญมี   20.0    หญิง           วิศวฯ  3.23       169.0
13         64014     ปรีชา   21.0     ชาย    Liberal Arts  3.45       164.0
14         64015     พิมพ์   22.0  Female             Sci  3.67       162.0
15         64016      ภูมิ   19.0       ช     วิทยาศาสตร์  3.89       173.0
16         64017      มานี   20.0       ญ  วิศวกรรมศาสตร์  3.01       166.0
17         64018      ยุพา   21.0    หญิง             NaN  3.23       161.0
18         64019     รัตนา    NaN     ชาย      ศิลปศาสตร์   NaN       174.0
19         64020     ลัดดา   22.0     NaN         Science  3.45       168.0

    น้ำหนัก_kg  ชั่วโมงเรียน_ต่อสัปดาห์ วันที่ลงทะเบียน
0         65.0                     15.0      2024-01-23
1         58.0                     20.0      2024-02-05
2          NaN                     25.0      2024-01-13
3         70.0                     10.0      2023-12-30
4         52.0                     30.0      2024-01-27
5         75.0                     12.0      2023-12-23
6         48.0                     35.0      2024-01-05
7         82.0                     18.0      2024-01-23
8         55.0                     22.0      2024-02-11
9         60.0                     28.0      2024-01-03
10        68.0                      NaN      2024-01-07
11         NaN                     16.0      2023-12-26
12        72.0                     24.0      2023-12-26
13        54.0                     19.0      2024-01-08
14        56.0                     26.0      2024-02-06
15        78.0                     14.0      2024-01-20
16        62.0                     21.0      2024-01-24
17        50.0                     27.0      2024-01-08
18        76.0                      NaN      2023-12-18
19        64.0                     23.0      2024-01-06  >

In [76]:
print(df.isna().sum())

รหัสนักศึกษา               0
ชื่อ                       1
อายุ                       3
เพศ                        2
คณะ                        2
GPA                        2
ส่วนสูง_cm                 1
น้ำหนัก_kg                 2
ชั่วโมงเรียน_ต่อสัปดาห์    2
วันที่ลงทะเบียน            0
dtype: int64

In [77]:
#เติมชื่อ
df.loc[df["รหัสนักศึกษา"] == 64003, "ชื่อ"] = "โอเดการ์ด"
#เติมคณะ
df.loc[df["รหัสนักศึกษา"] == 64011, "คณะ"] = "วิทยาศาสตร์"
df.loc[df["รหัสนักศึกษา"] == 64018, "คณะ"] = "ศิลปศาสตร์"
#เติมเพศที่หาย
df.loc[df["รหัสนักศึกษา"] == 64020, "เพศ"] = "หญิง"
print("หลังเติมค่า")
print(df)

หลังเติมค่า
    รหัสนักศึกษา       ชื่อ   อายุ     เพศ             คณะ   GPA  ส่วนสูง_cm  \
0          64001      สมชาย   20.0     ชาย     วิทยาศาสตร์  3.21       170.0
1          64002     สมหญิง   21.0    หญิง           วิทย์  3.45       165.0
2          64003  โอเดการ์ด    NaN    Male         Science  3.67       175.0
3          64004   สมศักดิ์   22.0       ช  คณะวิทยาศาสตร์ -1.00       168.0
4          64005       สมใจ   19.0       ญ           วิศวะ  3.89       160.0
5          64006      กานต์  150.0     ชาย     Engineering  3.12       172.0
6          64007      กิตติ   21.0    หญิง        วิศวกรรม  4.50       158.0
7          64008       จิรา   20.0       F      ศิลปศาสตร์  2.98       180.0
8          64009     ชนาธิป   23.0       M            Arts  3.34       163.0
9          64010       ดารา   21.0    หญิง           ศิลป์  3.56       167.0
10         64011       ธีระ    NaN     NaN     วิทยาศาสตร์  3.78         NaN
11         64012        นภา   22.0     ชาย           วิทย์   NaN       171.0
12         64013      บุญมี   20.0    หญิง           วิศวฯ  3.23       169.0
13         64014      ปรีชา   21.0     ชาย    Liberal Arts  3.45       164.0
14         64015      พิมพ์   22.0  Female             Sci  3.67       162.0
15         64016       ภูมิ   19.0       ช     วิทยาศาสตร์  3.89       173.0
16         64017       มานี   20.0       ญ  วิศวกรรมศาสตร์  3.01       166.0
17         64018       ยุพา   21.0    หญิง      ศิลปศาสตร์  3.23       161.0
18         64019      รัตนา    NaN     ชาย      ศิลปศาสตร์   NaN       174.0
19         64020      ลัดดา   22.0    หญิง         Science  3.45       168.0

    น้ำหนัก_kg  ชั่วโมงเรียน_ต่อสัปดาห์ วันที่ลงทะเบียน
0         65.0                     15.0      2024-01-23
1         58.0                     20.0      2024-02-05
2          NaN                     25.0      2024-01-13
3         70.0                     10.0      2023-12-30
4         52.0                     30.0      2024-01-27
5         75.0                     12.0      2023-12-23
6         48.0                     35.0      2024-01-05
7         82.0                     18.0      2024-01-23
8         55.0                     22.0      2024-02-11
9         60.0                     28.0      2024-01-03
10        68.0                      NaN      2024-01-07
11         NaN                     16.0      2023-12-26
12        72.0                     24.0      2023-12-26
13        54.0                     19.0      2024-01-08
14        56.0                     26.0      2024-02-06
15        78.0                     14.0      2024-01-20
16        62.0                     21.0      2024-01-24
17        50.0                     27.0      2024-01-08
18        76.0                      NaN      2023-12-18
19        64.0                     23.0      2024-01-06

In [78]:
#เติมค่าอายุที่หายไปด้วยค่าเฉลี่ย
df['อายุ'] = df['อายุ'].fillna(df['อายุ'].mean())
print("หลังเติมค่า")
print(df)

หลังเติมค่า
    รหัสนักศึกษา       ชื่อ        อายุ     เพศ             คณะ   GPA  \
0          64001      สมชาย   20.000000     ชาย     วิทยาศาสตร์  3.21
1          64002     สมหญิง   21.000000    หญิง           วิทย์  3.45
2          64003  โอเดการ์ด   28.470588    Male         Science  3.67
3          64004   สมศักดิ์   22.000000       ช  คณะวิทยาศาสตร์ -1.00
4          64005       สมใจ   19.000000       ญ           วิศวะ  3.89
5          64006      กานต์  150.000000     ชาย     Engineering  3.12
6          64007      กิตติ   21.000000    หญิง        วิศวกรรม  4.50
7          64008       จิรา   20.000000       F      ศิลปศาสตร์  2.98
8          64009     ชนาธิป   23.000000       M            Arts  3.34
9          64010       ดารา   21.000000    หญิง           ศิลป์  3.56
10         64011       ธีระ   28.470588     NaN     วิทยาศาสตร์  3.78
11         64012        นภา   22.000000     ชาย           วิทย์   NaN
12         64013      บุญมี   20.000000    หญิง           วิศวฯ  3.23
13         64014      ปรีชา   21.000000     ชาย    Liberal Arts  3.45
14         64015      พิมพ์   22.000000  Female             Sci  3.67
15         64016       ภูมิ   19.000000       ช     วิทยาศาสตร์  3.89
16         64017       มานี   20.000000       ญ  วิศวกรรมศาสตร์  3.01
17         64018       ยุพา   21.000000    หญิง      ศิลปศาสตร์  3.23
18         64019      รัตนา   28.470588     ชาย      ศิลปศาสตร์   NaN
19         64020      ลัดดา   22.000000    หญิง         Science  3.45

    ส่วนสูง_cm  น้ำหนัก_kg  ชั่วโมงเรียน_ต่อสัปดาห์ วันที่ลงทะเบียน
0        170.0        65.0                     15.0      2024-01-23
1        165.0        58.0                     20.0      2024-02-05
2        175.0         NaN                     25.0      2024-01-13
3        168.0        70.0                     10.0      2023-12-30
4        160.0        52.0                     30.0      2024-01-27
5        172.0        75.0                     12.0      2023-12-23
6        158.0        48.0                     35.0      2024-01-05
7        180.0        82.0                     18.0      2024-01-23
8        163.0        55.0                     22.0      2024-02-11
9        167.0        60.0                     28.0      2024-01-03
10         NaN        68.0                      NaN      2024-01-07
11       171.0         NaN                     16.0      2023-12-26
12       169.0        72.0                     24.0      2023-12-26
13       164.0        54.0                     19.0      2024-01-08
14       162.0        56.0                     26.0      2024-02-06
15       173.0        78.0                     14.0      2024-01-20
16       166.0        62.0                     21.0      2024-01-24
17       161.0        50.0                     27.0      2024-01-08
18       174.0        76.0                      NaN      2023-12-18
19       168.0        64.0                     23.0      2024-01-06

In [79]:
#เติมค่าเพศที่หายไปด้วยโหมด
df['เพศ'] = df['เพศ'].fillna(df['เพศ'].mode()[0])
print("หลังเติมค่า")
print(df)

หลังเติมค่า
    รหัสนักศึกษา       ชื่อ        อายุ     เพศ             คณะ   GPA  \
0          64001      สมชาย   20.000000     ชาย     วิทยาศาสตร์  3.21
1          64002     สมหญิง   21.000000    หญิง           วิทย์  3.45
2          64003  โอเดการ์ด   28.470588    Male         Science  3.67
3          64004   สมศักดิ์   22.000000       ช  คณะวิทยาศาสตร์ -1.00
4          64005       สมใจ   19.000000       ญ           วิศวะ  3.89
5          64006      กานต์  150.000000     ชาย     Engineering  3.12
6          64007      กิตติ   21.000000    หญิง        วิศวกรรม  4.50
7          64008       จิรา   20.000000       F      ศิลปศาสตร์  2.98
8          64009     ชนาธิป   23.000000       M            Arts  3.34
9          64010       ดารา   21.000000    หญิง           ศิลป์  3.56
10         64011       ธีระ   28.470588    หญิง     วิทยาศาสตร์  3.78
11         64012        นภา   22.000000     ชาย           วิทย์   NaN
12         64013      บุญมี   20.000000    หญิง           วิศวฯ  3.23
13         64014      ปรีชา   21.000000     ชาย    Liberal Arts  3.45
14         64015      พิมพ์   22.000000  Female             Sci  3.67
15         64016       ภูมิ   19.000000       ช     วิทยาศาสตร์  3.89
16         64017       มานี   20.000000       ญ  วิศวกรรมศาสตร์  3.01
17         64018       ยุพา   21.000000    หญิง      ศิลปศาสตร์  3.23
18         64019      รัตนา   28.470588     ชาย      ศิลปศาสตร์   NaN
19         64020      ลัดดา   22.000000    หญิง         Science  3.45

    ส่วนสูง_cm  น้ำหนัก_kg  ชั่วโมงเรียน_ต่อสัปดาห์ วันที่ลงทะเบียน
0        170.0        65.0                     15.0      2024-01-23
1        165.0        58.0                     20.0      2024-02-05
2        175.0         NaN                     25.0      2024-01-13
3        168.0        70.0                     10.0      2023-12-30
4        160.0        52.0                     30.0      2024-01-27
5        172.0        75.0                     12.0      2023-12-23
6        158.0        48.0                     35.0      2024-01-05
7        180.0        82.0                     18.0      2024-01-23
8        163.0        55.0                     22.0      2024-02-11
9        167.0        60.0                     28.0      2024-01-03
10         NaN        68.0                      NaN      2024-01-07
11       171.0         NaN                     16.0      2023-12-26
12       169.0        72.0                     24.0      2023-12-26
13       164.0        54.0                     19.0      2024-01-08
14       162.0        56.0                     26.0      2024-02-06
15       173.0        78.0                     14.0      2024-01-20
16       166.0        62.0                     21.0      2024-01-24
17       161.0        50.0                     27.0      2024-01-08
18       174.0        76.0                      NaN      2023-12-18
19       168.0        64.0                     23.0      2024-01-06

In [80]:
#แก้ไขค่าที่ผิดปกติ อายุเกิน 100
Q1 = df['อายุ'].quantile(0.25)
Q3 = df['อายุ'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
df_no_outliers = df[(df['อายุ'] >= lower_bound) & (df['อายุ'] <= upper_bound)]

print(f"\nขอบเขตล่าง - {lower_bound}")
print(f"ขอบเขตบน - {upper_bound}")
print(f"\nข้อมูลหลังกรองค่าผิดปกติ")
print(df_no_outliers)
print(f"\nค่าเฉลี่ยอายุ (หลังกรองค่าผิดปกติ) - {df_no_outliers['อายุ'].mean():.2f}")

ขอบเขตล่าง - 16.625
ขอบเขตบน - 25.625

ข้อมูลหลังกรองค่าผิดปกติ
    รหัสนักศึกษา      ชื่อ  อายุ     เพศ             คณะ   GPA  ส่วนสูง_cm  \
0          64001     สมชาย  20.0     ชาย     วิทยาศาสตร์  3.21       170.0
1          64002    สมหญิง  21.0    หญิง           วิทย์  3.45       165.0
3          64004  สมศักดิ์  22.0       ช  คณะวิทยาศาสตร์ -1.00       168.0
4          64005      สมใจ  19.0       ญ           วิศวะ  3.89       160.0
6          64007     กิตติ  21.0    หญิง        วิศวกรรม  4.50       158.0
7          64008      จิรา  20.0       F      ศิลปศาสตร์  2.98       180.0
8          64009    ชนาธิป  23.0       M            Arts  3.34       163.0
9          64010      ดารา  21.0    หญิง           ศิลป์  3.56       167.0
11         64012       นภา  22.0     ชาย           วิทย์   NaN       171.0
12         64013     บุญมี  20.0    หญิง           วิศวฯ  3.23       169.0
13         64014     ปรีชา  21.0     ชาย    Liberal Arts  3.45       164.0
14         64015     พิมพ์  22.0  Female             Sci  3.67       162.0
15         64016      ภูมิ  19.0       ช     วิทยาศาสตร์  3.89       173.0
16         64017      มานี  20.0       ญ  วิศวกรรมศาสตร์  3.01       166.0
17         64018      ยุพา  21.0    หญิง      ศิลปศาสตร์  3.23       161.0
19         64020     ลัดดา  22.0    หญิง         Science  3.45       168.0

    น้ำหนัก_kg  ชั่วโมงเรียน_ต่อสัปดาห์ วันที่ลงทะเบียน
0         65.0                     15.0      2024-01-23
1         58.0                     20.0      2024-02-05
3         70.0                     10.0      2023-12-30
4         52.0                     30.0      2024-01-27
6         48.0                     35.0      2024-01-05
7         82.0                     18.0      2024-01-23
8         55.0                     22.0      2024-02-11
9         60.0                     28.0      2024-01-03
11         NaN                     16.0      2023-12-26
12        72.0                     24.0      2023-12-26
13        54.0                     19.0      2024-01-08
14        56.0                     26.0      2024-02-06
15        78.0                     14.0      2024-01-20
16        62.0                     21.0      2024-01-24
17        50.0                     27.0      2024-01-08
19        64.0                     23.0      2024-01-06

ค่าเฉลี่ยอายุ (หลังกรองค่าผิดปกติ) - 20.88

In [81]:
#แก้ไขค่าที่ผิดปกติ GPA
Q1 = df['GPA'].quantile(0.25)
Q3 = df['GPA'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
df_no_outliers = df[(df['GPA'] >= lower_bound) & (df['GPA'] <= upper_bound)]

print(f"\nขอบเขตล่าง - {lower_bound:.2f}")
print(f"ขอบเขตบน - {upper_bound:.2f}")
print(f"\nข้อมูลหลังกรองค่าผิดปกติ")
print(df_no_outliers)
print(f"\nค่าเฉลี่ย GPA (หลังกรองค่าผิดปกติ) - {df_no_outliers['GPA'].mean():.2f}")

ขอบเขตล่าง - 2.53
ขอบเขตบน - 4.35

ข้อมูลหลังกรองค่าผิดปกติ
    รหัสนักศึกษา       ชื่อ        อายุ     เพศ             คณะ   GPA  \
0          64001      สมชาย   20.000000     ชาย     วิทยาศาสตร์  3.21
1          64002     สมหญิง   21.000000    หญิง           วิทย์  3.45
2          64003  โอเดการ์ด   28.470588    Male         Science  3.67
4          64005       สมใจ   19.000000       ญ           วิศวะ  3.89
5          64006      กานต์  150.000000     ชาย     Engineering  3.12
7          64008       จิรา   20.000000       F      ศิลปศาสตร์  2.98
8          64009     ชนาธิป   23.000000       M            Arts  3.34
9          64010       ดารา   21.000000    หญิง           ศิลป์  3.56
10         64011       ธีระ   28.470588    หญิง     วิทยาศาสตร์  3.78
12         64013      บุญมี   20.000000    หญิง           วิศวฯ  3.23
13         64014      ปรีชา   21.000000     ชาย    Liberal Arts  3.45
14         64015      พิมพ์   22.000000  Female             Sci  3.67
15         64016       ภูมิ   19.000000       ช     วิทยาศาสตร์  3.89
16         64017       มานี   20.000000       ญ  วิศวกรรมศาสตร์  3.01
17         64018       ยุพา   21.000000    หญิง      ศิลปศาสตร์  3.23
19         64020      ลัดดา   22.000000    หญิง         Science  3.45

    ส่วนสูง_cm  น้ำหนัก_kg  ชั่วโมงเรียน_ต่อสัปดาห์ วันที่ลงทะเบียน
0        170.0        65.0                     15.0      2024-01-23
1        165.0        58.0                     20.0      2024-02-05
2        175.0         NaN                     25.0      2024-01-13
4        160.0        52.0                     30.0      2024-01-27
5        172.0        75.0                     12.0      2023-12-23
7        180.0        82.0                     18.0      2024-01-23
8        163.0        55.0                     22.0      2024-02-11
9        167.0        60.0                     28.0      2024-01-03
10         NaN        68.0                      NaN      2024-01-07
12       169.0        72.0                     24.0      2023-12-26
13       164.0        54.0                     19.0      2024-01-08
14       162.0        56.0                     26.0      2024-02-06
15       173.0        78.0                     14.0      2024-01-20
16       166.0        62.0                     21.0      2024-01-24
17       161.0        50.0                     27.0      2024-01-08
19       168.0        64.0                     23.0      2024-01-06

ค่าเฉลี่ย GPA (หลังกรองค่าผิดปกติ) - 3.43

In [82]:
df['วันที่ลงทะเบียน'] = pd.to_datetime(df['วันที่ลงทะเบียน'])

In [83]:
def normalize_gender(g):
    if pd.isna(g):
        return 'ไม่ระบุ'
    g = str(g).lower()
    if g in ['ชาย', 'ช', 'male', 'm']:
        return 'ชาย'
    elif g in ['หญิง', 'ญ', 'female', 'f']:
        return 'หญิง'
    else:
        return 'ไม่ระบุ'

In [84]:
#สร้างฟีเจอร์ BMI (น้ำหนัก/ส่วนสูง^2)
df['ส่วนสูง_เมตร'] = df['ส่วนสูง_cm'] / 100
df['BMI'] = df['น้ำหนัก_kg'] / (df['ส่วนสูง_เมตร'] ** 2)
print(df)

    รหัสนักศึกษา       ชื่อ        อายุ     เพศ             คณะ   GPA  \
0          64001      สมชาย   20.000000     ชาย     วิทยาศาสตร์  3.21
1          64002     สมหญิง   21.000000    หญิง           วิทย์  3.45
2          64003  โอเดการ์ด   28.470588    Male         Science  3.67
3          64004   สมศักดิ์   22.000000       ช  คณะวิทยาศาสตร์ -1.00
4          64005       สมใจ   19.000000       ญ           วิศวะ  3.89
5          64006      กานต์  150.000000     ชาย     Engineering  3.12
6          64007      กิตติ   21.000000    หญิง        วิศวกรรม  4.50
7          64008       จิรา   20.000000       F      ศิลปศาสตร์  2.98
8          64009     ชนาธิป   23.000000       M            Arts  3.34
9          64010       ดารา   21.000000    หญิง           ศิลป์  3.56
10         64011       ธีระ   28.470588    หญิง     วิทยาศาสตร์  3.78
11         64012        นภา   22.000000     ชาย           วิทย์   NaN
12         64013      บุญมี   20.000000    หญิง           วิศวฯ  3.23
13         64014      ปรีชา   21.000000     ชาย    Liberal Arts  3.45
14         64015      พิมพ์   22.000000  Female             Sci  3.67
15         64016       ภูมิ   19.000000       ช     วิทยาศาสตร์  3.89
16         64017       มานี   20.000000       ญ  วิศวกรรมศาสตร์  3.01
17         64018       ยุพา   21.000000    หญิง      ศิลปศาสตร์  3.23
18         64019      รัตนา   28.470588     ชาย      ศิลปศาสตร์   NaN
19         64020      ลัดดา   22.000000    หญิง         Science  3.45

    ส่วนสูง_cm  น้ำหนัก_kg  ชั่วโมงเรียน_ต่อสัปดาห์ วันที่ลงทะเบียน  \
0        170.0        65.0                     15.0      2024-01-23
1        165.0        58.0                     20.0      2024-02-05
2        175.0         NaN                     25.0      2024-01-13
3        168.0        70.0                     10.0      2023-12-30
4        160.0        52.0                     30.0      2024-01-27
5        172.0        75.0                     12.0      2023-12-23
6        158.0        48.0                     35.0      2024-01-05
7        180.0        82.0                     18.0      2024-01-23
8        163.0        55.0                     22.0      2024-02-11
9        167.0        60.0                     28.0      2024-01-03
10         NaN        68.0                      NaN      2024-01-07
11       171.0         NaN                     16.0      2023-12-26
12       169.0        72.0                     24.0      2023-12-26
13       164.0        54.0                     19.0      2024-01-08
14       162.0        56.0                     26.0      2024-02-06
15       173.0        78.0                     14.0      2024-01-20
16       166.0        62.0                     21.0      2024-01-24
17       161.0        50.0                     27.0      2024-01-08
18       174.0        76.0                      NaN      2023-12-18
19       168.0        64.0                     23.0      2024-01-06

    ส่วนสูง_เมตร        BMI
0           1.70  22.491349
1           1.65  21.303949
2           1.75        NaN
3           1.68  24.801587
4           1.60  20.312500
5           1.72  25.351541
6           1.58  19.227688
7           1.80  25.308642
8           1.63  20.700817
9           1.67  21.513859
10           NaN        NaN
11          1.71        NaN
12          1.69  25.209201
13          1.64  20.077335
14          1.62  21.338211
15          1.73  26.061679
16          1.66  22.499637
17          1.61  19.289379
18          1.74  25.102391
19          1.68  22.675737

In [85]:
#สร้างฟีเจอร์แบ่งช่วงอายุ (bucket)
bins = [0, 20, 25, 100]
labels = ['น้อยกว่า 20', '20-25', 'มากกว่า 25']
df['ช่วงอายุ'] = pd.cut(df['อายุ'], bins=bins, labels=labels, right=False)
print(df)

    รหัสนักศึกษา       ชื่อ        อายุ     เพศ             คณะ   GPA  \
0          64001      สมชาย   20.000000     ชาย     วิทยาศาสตร์  3.21
1          64002     สมหญิง   21.000000    หญิง           วิทย์  3.45
2          64003  โอเดการ์ด   28.470588    Male         Science  3.67
3          64004   สมศักดิ์   22.000000       ช  คณะวิทยาศาสตร์ -1.00
4          64005       สมใจ   19.000000       ญ           วิศวะ  3.89
5          64006      กานต์  150.000000     ชาย     Engineering  3.12
6          64007      กิตติ   21.000000    หญิง        วิศวกรรม  4.50
7          64008       จิรา   20.000000       F      ศิลปศาสตร์  2.98
8          64009     ชนาธิป   23.000000       M            Arts  3.34
9          64010       ดารา   21.000000    หญิง           ศิลป์  3.56
10         64011       ธีระ   28.470588    หญิง     วิทยาศาสตร์  3.78
11         64012        นภา   22.000000     ชาย           วิทย์   NaN
12         64013      บุญมี   20.000000    หญิง           วิศวฯ  3.23
13         64014      ปรีชา   21.000000     ชาย    Liberal Arts  3.45
14         64015      พิมพ์   22.000000  Female             Sci  3.67
15         64016       ภูมิ   19.000000       ช     วิทยาศาสตร์  3.89
16         64017       มานี   20.000000       ญ  วิศวกรรมศาสตร์  3.01
17         64018       ยุพา   21.000000    หญิง      ศิลปศาสตร์  3.23
18         64019      รัตนา   28.470588     ชาย      ศิลปศาสตร์   NaN
19         64020      ลัดดา   22.000000    หญิง         Science  3.45

    ส่วนสูง_cm  น้ำหนัก_kg  ชั่วโมงเรียน_ต่อสัปดาห์ วันที่ลงทะเบียน  \
0        170.0        65.0                     15.0      2024-01-23
1        165.0        58.0                     20.0      2024-02-05
2        175.0         NaN                     25.0      2024-01-13
3        168.0        70.0                     10.0      2023-12-30
4        160.0        52.0                     30.0      2024-01-27
5        172.0        75.0                     12.0      2023-12-23
6        158.0        48.0                     35.0      2024-01-05
7        180.0        82.0                     18.0      2024-01-23
8        163.0        55.0                     22.0      2024-02-11
9        167.0        60.0                     28.0      2024-01-03
10         NaN        68.0                      NaN      2024-01-07
11       171.0         NaN                     16.0      2023-12-26
12       169.0        72.0                     24.0      2023-12-26
13       164.0        54.0                     19.0      2024-01-08
14       162.0        56.0                     26.0      2024-02-06
15       173.0        78.0                     14.0      2024-01-20
16       166.0        62.0                     21.0      2024-01-24
17       161.0        50.0                     27.0      2024-01-08
18       174.0        76.0                      NaN      2023-12-18
19       168.0        64.0                     23.0      2024-01-06

    ส่วนสูง_เมตร        BMI     ช่วงอายุ
0           1.70  22.491349        20-25
1           1.65  21.303949        20-25
2           1.75        NaN   มากกว่า 25
3           1.68  24.801587        20-25
4           1.60  20.312500  น้อยกว่า 20
5           1.72  25.351541          NaN
6           1.58  19.227688        20-25
7           1.80  25.308642        20-25
8           1.63  20.700817        20-25
9           1.67  21.513859        20-25
10           NaN        NaN   มากกว่า 25
11          1.71        NaN        20-25
12          1.69  25.209201        20-25
13          1.64  20.077335        20-25
14          1.62  21.338211        20-25
15          1.73  26.061679  น้อยกว่า 20
16          1.66  22.499637        20-25
17          1.61  19.289379        20-25
18          1.74  25.102391   มากกว่า 25
19          1.68  22.675737        20-25

In [86]:
df = pd.get_dummies(df, columns=['เพศ', 'คณะ', 'ช่วงอายุ'], drop_first=True)

In [87]:
print(df.isna().sum())

รหัสนักศึกษา               0
ชื่อ                       0
อายุ                       0
GPA                        2
ส่วนสูง_cm                 1
น้ำหนัก_kg                 2
ชั่วโมงเรียน_ต่อสัปดาห์    2
วันที่ลงทะเบียน            0
ส่วนสูง_เมตร               1
BMI                        3
เพศ_Female                 0
เพศ_M                      0
เพศ_Male                   0
เพศ_ช                      0
เพศ_ชาย                    0
เพศ_ญ                      0
เพศ_หญิง                   0
คณะ_Engineering            0
คณะ_Liberal Arts           0
คณะ_Sci                    0
คณะ_Science                0
คณะ_คณะวิทยาศาสตร์         0
คณะ_วิทยาศาสตร์            0
คณะ_วิทย์                  0
คณะ_วิศวกรรม               0
คณะ_วิศวกรรมศาสตร์         0
คณะ_วิศวฯ                  0
คณะ_วิศวะ                  0
คณะ_ศิลปศาสตร์             0
คณะ_ศิลป์                  0
ช่วงอายุ_20-25             0
ช่วงอายุ_มากกว่า 25        0
dtype: int64

In [88]:
# เติมค่าตัวเลขด้วยค่าเฉลี่ย
df['น้ำหนัก_kg'] = df['น้ำหนัก_kg'].fillna(df['น้ำหนัก_kg'].mean())
df['ส่วนสูง_cm'] = df['ส่วนสูง_cm'].fillna(df['ส่วนสูง_cm'].mean())
df['GPA'] = df['GPA'].fillna(df['GPA'].mean())

# เติมค่าข้อความ
df['ชื่อ'] = df['ชื่อ'].fillna('ไม่ระบุ')

In [89]:
df = df.dropna(subset=['น้ำหนัก_kg', 'ส่วนสูง_cm', 'GPA'])

In [90]:
df['ส่วนสูง_เมตร'] = df['ส่วนสูง_cm'] / 100
df['BMI'] = df['น้ำหนัก_kg'] / (df['ส่วนสูง_เมตร'] ** 2)

In [91]:
df['ชั่วโมงเรียน_ต่อสัปดาห์'] = df['ชั่วโมงเรียน_ต่อสัปดาห์'].fillna(df['ชั่วโมงเรียน_ต่อสัปดาห์'].mean())

In [92]:
df['ส่วนสูง_เมตร'] = df['ส่วนสูง_cm'] / 100
df['BMI'] = df['น้ำหนัก_kg'] / (df['ส่วนสูง_เมตร'] ** 2)

In [93]:
print(df.isna().sum()[df.isna().sum() > 0])

Series([], dtype: int64)

In [94]:
print(df)

    รหัสนักศึกษา       ชื่อ        อายุ       GPA  ส่วนสูง_cm  น้ำหนัก_kg  \
0          64001      สมชาย   20.000000  3.210000  170.000000   65.000000
1          64002     สมหญิง   21.000000  3.450000  165.000000   58.000000
2          64003  โอเดการ์ด   28.470588  3.670000  175.000000   63.611111
3          64004   สมศักดิ์   22.000000 -1.000000  168.000000   70.000000
4          64005       สมใจ   19.000000  3.890000  160.000000   52.000000
5          64006      กานต์  150.000000  3.120000  172.000000   75.000000
6          64007      กิตติ   21.000000  4.500000  158.000000   48.000000
7          64008       จิรา   20.000000  2.980000  180.000000   82.000000
8          64009     ชนาธิป   23.000000  3.340000  163.000000   55.000000
9          64010       ดารา   21.000000  3.560000  167.000000   60.000000
10         64011       ธีระ   28.470588  3.780000  167.684211   68.000000
11         64012        นภา   22.000000  3.246111  171.000000   63.611111
12         64013      บุญมี   20.000000  3.230000  169.000000   72.000000
13         64014      ปรีชา   21.000000  3.450000  164.000000   54.000000
14         64015      พิมพ์   22.000000  3.670000  162.000000   56.000000
15         64016       ภูมิ   19.000000  3.890000  173.000000   78.000000
16         64017       มานี   20.000000  3.010000  166.000000   62.000000
17         64018       ยุพา   21.000000  3.230000  161.000000   50.000000
18         64019      รัตนา   28.470588  3.246111  174.000000   76.000000
19         64020      ลัดดา   22.000000  3.450000  168.000000   64.000000

    ชั่วโมงเรียน_ต่อสัปดาห์ วันที่ลงทะเบียน  ส่วนสูง_เมตร        BMI  ...  \
0                 15.000000      2024-01-23      1.700000  22.491349  ...
1                 20.000000      2024-02-05      1.650000  21.303949  ...
2                 25.000000      2024-01-13      1.750000  20.770975  ...
3                 10.000000      2023-12-30      1.680000  24.801587  ...
4                 30.000000      2024-01-27      1.600000  20.312500  ...
5                 12.000000      2023-12-23      1.720000  25.351541  ...
6                 35.000000      2024-01-05      1.580000  19.227688  ...
7                 18.000000      2024-01-23      1.800000  25.308642  ...
8                 22.000000      2024-02-11      1.630000  20.700817  ...
9                 28.000000      2024-01-03      1.670000  21.513859  ...
10                21.388889      2024-01-07      1.676842  24.183802  ...
11                16.000000      2023-12-26      1.710000  21.754082  ...
12                24.000000      2023-12-26      1.690000  25.209201  ...
13                19.000000      2024-01-08      1.640000  20.077335  ...
14                26.000000      2024-02-06      1.620000  21.338211  ...
15                14.000000      2024-01-20      1.730000  26.061679  ...
16                21.000000      2024-01-24      1.660000  22.499637  ...
17                27.000000      2024-01-08      1.610000  19.289379  ...
18                21.388889      2023-12-18      1.740000  25.102391  ...
19                23.000000      2024-01-06      1.680000  22.675737  ...

    คณะ_วิทยาศาสตร์  คณะ_วิทย์  คณะ_วิศวกรรม  คณะ_วิศวกรรมศาสตร์  คณะ_วิศวฯ  \
0              True      False         False               False      False
1             False       True         False               False      False
2             False      False         False               False      False
3             False      False         False               False      False
4             False      False         False               False      False
5             False      False         False               False      False
6             False      False          True               False      False
7             False      False         False               False      False
8             False      False         False               False      False
9             False      False         False               False      False
10             True      False         False               False      False
11            False       True         False               False      False
12            False      False         False               False       True
13            False      False         False               False      False
14            False      False         False               False      False
15             True      False         False               False      False
16            False      False         False                True      False
17            False      False         False               False      False
18            False      False         False               False      False
19            False      False         False               False      False

    คณะ_วิศวะ  คณะ_ศิลปศาสตร์  คณะ_ศิลป์  ช่วงอายุ_20-25  ช่วงอายุ_มากกว่า 25
0       False           False      False            True                False
1       False           False      False            True                False
2       False           False      False           False                 True
3       False           False      False            True                False
4        True           False      False           False                False
5       False           False      False           False                False
6       False           False      False            True                False
7       False            True      False            True                False
8       False           False      False            True                False
9       False           False       True            True                False
10      False           False      False           False                 True
11      False           False      False            True                False
12      False           False      False            True                False
13      False           False      False            True                False
14      False           False      False            True                False
15      False           False      False           False                False
16      False           False      False            True                False
17      False            True      False            True                False
18      False            True      False           False                 True
19      False           False      False            True                False

[20 rows x 32 columns]